INSERT INTO products (title, price) VALUES ('Samsung X5 silver', 1060);
INSERT INTO products (title, price) VALUES ('Samsung X5 gold', 1876);
INSERT INTO products (title, price) VALUES ('Samsung X5', 1234);
INSERT INTO products (title, price) VALUES ('Samsung X10', 567);
INSERT INTO products (title, price) VALUES ('Samsung X22', 960);
INSERT INTO products (title, price) VALUES ('Samsung A55', 1260);
INSERT INTO products (title, price) VALUES ('Samsung X5', 1110);
INSERT INTO products (title, price) VALUES ('Samsung X9', 1200);
INSERT INTO products (title, price) VALUES ('Samsung XG45', 980);
INSERT INTO products (title, price) VALUES ('iPhone X silver', 1099);
INSERT INTO products (title, price) VALUES ('iPhone X gold', 1099);
INSERT INTO products (title, price) VALUES ('iPhone 7', 950);
INSERT INTO products (title, price) VALUES ('iPhone 6', 890);
INSERT INTO products (title, price) VALUES ('iPhone 8', 990);
INSERT INTO products (title, price) VALUES ('iPhone 11', 1190);
INSERT INTO products (title, price) VALUES ('iPhone 14', 2110);
INSERT INTO products (title, price) VALUES ('iPhone 12', 1290);
INSERT INTO products (title, price) VALUES ('iPhone 7 blue', 950);
INSERT INTO products (title, price) VALUES ('Xiaomi X silver', 1099);
INSERT INTO products (title, price) VALUES ('Xiaomi X gold', 1099);
INSERT INTO products (title, price) VALUES ('Xiaomi 7', 950);
INSERT INTO products (title, price) VALUES ('Xiaomi 6', 890);
INSERT INTO products (title, price) VALUES ('Xiaomi 8', 990);
INSERT INTO products (title, price) VALUES ('Xiaomi 11', 1090);
INSERT INTO products (title, price) VALUES ('Xiaomi 14', 2110);
INSERT INTO products (title, price) VALUES ('Xiaomi 12', 1290);
INSERT INTO products (title, price) VALUES ('Xiaomi 7 red', 950);
INSERT INTO products (title, price) VALUES ('Oppo silver', 1099);
INSERT INTO products (title, price) VALUES ('Oppo gold', 1099);
INSERT INTO products (title, price) VALUES ('Oppo 7', 950);
INSERT INTO products (title, price) VALUES ('Oppo 6', 855);
INSERT INTO products (title, price) VALUES ('Oppo 8', 955);
INSERT INTO products (title, price) VALUES ('Oppo 11', 1055);
INSERT INTO products (title, price) VALUES ('Oppo 14', 1110);
INSERT INTO products (title, price) VALUES ('Oppo 12', 1255);
INSERT INTO products (title, price) VALUES ('Oppo 7 red', 950);
