INSERT INTO products (title, price, category_id) VALUES ('iPhone 12', 1350, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone X', 550, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 11', 750, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 7', 570, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 6', 250, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 5S', 720, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 13', 650, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 14', 350, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone 4', 450, 1);
INSERT INTO products (title, price, category_id) VALUES ('iPhone X', 650, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei P9 red', 650, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei P9 yellow', 950, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei P9 black', 1050, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi', 350, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei X3', 559, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei P7', 659, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei V2', 689, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei One', 690, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei P9 pink', 1450, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi S', 1250, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Note', 1450, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi XC', 1050, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi 1', 950, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi 1', 850, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi 2 black', 350, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi 4 yellow', 790, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi BT', 1200, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi X', 1220, 1);
INSERT INTO products (title, price, category_id) VALUES ('Xiaomi Redmi N', 1060, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X5 silver', 1060, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X5 gold', 1876, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X5', 1234, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X10', 567, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X22', 960, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung A55', 1260, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X5', 1110, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X9', 1200, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung XG45', 980, 1);
INSERT INTO products (title, price, category_id) VALUES ('Huawei 9S', 460, 1);
INSERT INTO products (title, price, category_id) VALUES ('Samsung X6', 780, 1);
