INSERT INTO categories (id, name) VALUES (1, 'phone');
INSERT INTO categories (id, name) VALUES (2, 'toys');
INSERT INTO categories (id, name) VALUES (3, 'tools');
INSERT INTO products (id, title, price, category_id) VALUES (1, 'Samsung X9', 1200, 1);
INSERT INTO products (id, title, price, category_id) VALUES (2, 'Huawei 9S', 460, 1);
INSERT INTO products (id, title, price, category_id) VALUES (3, 'Samsung X6', 780, 1);
INSERT INTO products (id, title, price, category_id) VALUES (4, 'HotWheels', 100, 2);
INSERT INTO products (id, title, price, category_id) VALUES (5, 'Barby', 260, 2);
INSERT INTO products (id, title, price, category_id) VALUES (6, 'Pikachu', 180, 2);
INSERT INTO products (id, title, price, category_id) VALUES (7, 'Drill', 50, 3);
INSERT INTO products (id, title, price, category_id) VALUES (8, 'Hammer', 26, 3);
INSERT INTO products (id, title, price, category_id) VALUES (9, 'Screwdriver', 18, 3);